### PR TITLE
Unsubscribe link

### PR DESCRIPTION
**Pull request by adriananderegg**
#92 
adds link to unsubscribe page 
differentiates between html/multipart email and plaintext

### CODE REVIEW

**Comment by RolandStuder** [comment]
Cool thx, but I guess this needs more work and testing:

* [ ] Currently a person would still need to login to unsubscribe (which of course is still much better than not giving any option). But of course adding the possibility to unsubscribe would need some token per person, which means more stuff we need to save... more complexity.
* [ ] Maybe the html link should have some minimal styles, to make sure it is actually visible (background-color and color and text-decoration).
* [ ] Must be tested with real mails on the integration environment

**Comment by RolandStuder** [comment]
Cant a multipart email also have a plain text part as an alternative to the html part? this should be changed as well? And can't there be a multipart message without html, just a plain text message with an attachement, for example?

**Comment by adriananderegg** [comment]
I'll check on the multipart emails. currently there are no tests defined with multipart emails, so I'll have a look at this in general. 

and include some styles for the link. 

unsubscribe without login: I would there wait for tokenized logins as general feature. also requested in #606

**Comment by psunix** [comment]
wird vom BBT geprüft

**Comment by psunix** [comment]
wir haben die Änderungen in einen neuen PR übernommen: #1160

**Pull request closed without merging**
