### PR TITLE
Efficient screenspace-use on mobile

### PR DESCRIPTION
**Pull request by manuelmeister**
<table><tr><td>Before<br>before</td><td>After<br>after</tr></table>

It only changes the mobile styles

### CODE REVIEW

**Comment by carlobeltrame** [comment]
Thanks!

**Comment by fossil12** [comment]
This breaks some of the layout in the hitobito_jubla wagon. 

I haven't investigated all the changes, but at least this line overrides the new default: https://github.com/hitobito/hitobito_jubla/blob/91fcbc9a1f7336bd904a7110296ac0cfdc498093/app/assets/stylesheets/hitobito/customizable/_wagon.scss#L111

**Comment by manuelmeister** [comment]
Can you please share a screenshot?

Am Sa., 14. März 2020 um 22:15 Uhr schrieb David Keller <
notifications@github.com>:

**Comment by fossil12** [comment]
mobile

It overflows and activates horizontal scrolling.

**Comment by manuelmeister** [comment]
What happens if you remove this line:
https://github.com/hitobito/hitobito_jubla/blob/91fcbc9a1f7336bd904a7110296ac0cfdc498093/app/assets/stylesheets/hitobito/customizable/_wagon.scss#L111

**Comment by manuelmeister** [comment]
Probably also change
```diff
#page {
-  padding: 0 0 30px 0;
-  margin: 20px 0 20px;
   background: none;

-  @include responsive(mediaTablet) {
-    padding: 0 20px 30px 20px;
-    margin: 20px 0;
-  }
}

.sheet.parent {
-  padding-bottom: 1px;
   background: lighten($grayLighter, 1%);
   @include single-box-shadow($grayDarker, 0, 2px, 8px);
   .sheet {
-    margin: 0 -10px -30px 10px;
     &.parent {
       background: lighten($grayLighter, 3%);
     }
   }
}
```

**Comment by fossil12** [comment]
Unfortunately I don't have a local testing setup, but I tried to reproduce your changes using the web inspector and it looks good to me. 👍 

mobile_new

**Comment by manuelmeister** [comment]
Me neither. You can create a pull request for the hitobito_jubla wagon (If the changes don't break the desktop view).

**Comment by carlobeltrame** [comment]
Thanks for the investigations! This should be fixed now and deployed to integration jubla.puzzle.ch

**Comment by manuelmeister** [comment]
How can I test it?

**Comment by carlobeltrame** [comment]
I created an account for you on Jubla Integration (jubla.puzzle.ch)

**Comment by manuelmeister** [comment]
The same changes probably need to be applied on hitobito_pbs in https://github.com/hitobito/hitobito_pbs/blob/f6e3631fbe07dfcb2599269f7234fb2d2cab9a1a/app/assets/stylesheets/hitobito/customizable/_wagon.scss

**Comment by manuelmeister** [comment]
Aussderdem wäre es visuell schöner, in `hitobito` noch das hinzugefügt würde.
```scss
.level {
    padding: 16px 10px 0 10px;
    @include responsive(mediaTablet) {
       padding: 16px 20px 0 20px;
    }
}
```

**Comment by manuelmeister** [comment]
Ich habe die Integration getestet und die sieht wie erwartet aus. Danke!

**Comment by fossil12** [comment]
@carlobeltrame Thank you for the fix. Looks good to me. 👍

**Pull request merged**
